apiVersion: ENC[AES256_GCM,data:CbcvNfymERecENqUUafDNDjtcyTL4kS6gVAS,iv:rizEsye7fR5WOWBM96jhXmM1nIeXAnHFvLPvtM5XjAo=,tag:Q9iqhv9BNdmSNP1F1ElrXg==,type:str]
kind: ENC[AES256_GCM,data:6TmDyZPx8Ota2g==,iv:3NnMv4gyopR8uAfQL9bnq5t3Xm+s+M/p/eB0rJ8NofU=,tag:/AVDV5rdk0qhzFZKhNG4Lg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0ujLKch2EFhIXZ0cKw==,iv:gSGSJ871TDGS0iVb8KckkVO78UVDo6/lb/sjemYa8y4=,tag:QW1HWTdww9srnwLL4IvkWA==,type:str]
spec:
    Data:
        data-password: ENC[AES256_GCM,data:3FhogfsEP8CycZDfNqKLMg==,iv:WCj8bab5oRH6H2bCKB2P7Q0NvNo1+L4ejt2jsyNmd2E=,tag:/TH6hMKW33iD50MD8UEgKg==,type:str]
        data-name1: ENC[AES256_GCM,data:fdgonIV3AZT3noJvzDXGyH8=,iv:1PFcKzxDmUUXczk/gVjjgB1zQgCeTKhdkUA9fCF/lSA=,tag:t/nrP4pWACfBFo/9ObwUWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19tfqxgdgx3fe96j8fyy0c65nsfj8ku8sl4ccfxnzpn3xpakylg5s8sgac7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ekhnRFpKeW1ueGRadTNo
            UGdibmUxNDl4cCtuV3Ayb0lRNUJoY0lKZENNClp6YnN5cW90cWpDaEFHVGxVaWkw
            aklGT3J1RldJdTZtYldraFJRT0VzcjAKLS0tIEVLV2daZHh4ZlNBcGYwaURoYVFN
            cFZJSVFBMmhQaHJFejMxZUlZK21sWTQKW6TbGUUUlgjanM/B70DoMrARRSu2N6Iu
            VUV9jDJMRhpISm0HzORcEKeJyUMZSOczt5Rs3K1LFDnssIa5xZVmww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17pnpp9prret49zu3ppzafgujrzp5apx6cp3uds6k3hvgyvjmwe0qgywte0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdmo1YUdWNGl2MS80L01L
            c3pXakZxWXY4ZXh3M3dXckJYWU1lQnV5bWhjCmNqc3R5L1FyVjFDY3lkUG0wdGNC
            eFUrRUFwUHRKZVE4UHBSYWl2czQxblUKLS0tIDYvRDFSTUo3VWlnUkxVMndnUUJ2
            YW5qWWFEZCt1U1hCWlZxVVhVVEZvdjQKWAAjp9VN7mARRkmfReLS47zu5wzT3T/z
            CABeuGG4LMJptTJrjP1/jDOYR/v1BeMIsqIZUtzZPxzlT0yz1PiNkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-11T10:16:37Z"
    mac: ENC[AES256_GCM,data:av+kEX+j6II04xi7IeWXsqsPlt45UUgOBPV+wggPpAGFQ6D0Wsh8VFd0upf0aTmYzu5sHRLi5I92w2VBsnaFiOQrTucIf8EAfod/aGPR8Mptr541QSj0T32KXXEJ/lTtYLIPYHiBfFxi04U0Ip7Dw1pbqifusRg8ftMyJ946LiI=,iv:ntf2n3pRF9kAS9i9wtemp3zn2zSkU/5eb+EMCQ5gVqg=,tag:qMdVW8gSi3BGvbpW1k+A5g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
